### ISSUE TITLE
Add ViT models

### ISSUE THREAD

**Issue by TrNgTinh** [NNDam/adaface-partialfc#2]
1. Cảm ơn anh vì 1 repo hữu ích ạ. Em thấy trong phần Todo anh có ghi là Add Vit models. Theo em biết là backbone này có được bên InsightFace cập nhật rồi đúng không ạ?. Trước đây em đã chạy thử backbone này và kết quả khá tốt nhưng nhược điểm là model khá nặng.
2. Em có custome 1 backbone của 1 kiến trúc khác, cũng sử dụng cơ chế Attention. Link paper & code [EfficientFormer](https://github.com/snap-research/EfficientFormer). Sau khi train xong trên tập WF260, tập val lfw có độ chính xác là 0.99833. Model này chỉ nặng 46MB. Loss em sử dụng là ArcFace
3. Nếu anh muốn thử em có thể đóng góp backbone mới này.
4. Em cảm ơn.

**Comment by NNDam** [comment]
Chào bạn, mình tạo ra repo này mục đích chính là cải thiện độ chính xác model hiện tại của mình với các trường hợp mờ, nhòe. Dữ liệu private của mình khá là lớn (5M ids, 105M ảnh), đã training với phiên bản Cosface và Arcface và kết quả rất tốt, tuy nhiên kết quả của Adaface trong quá trình training không đạt như mong đợi (quá trình hội tụ chậm hơn, acc ver cũng thấp hơn) nên mình không tiếp tục sử dụng Adaface nữa mà đơn giản chỉ sử dụng Cosface + Augment thông thường.
Thông tin đến bạn.

**Comment by TranThanh96** [comment]
@NNDam bác cho em hỏi, trên bảng xếp hạng nist, với data  (5M ids, 105M ảnh) của bác, bác train model và submit với tên công ty là icomm phải k ạ ?
