### ISSUE TITLE
reduce_scatter的处理是为什么呢

### ISSUE THREAD

**Issue by qiu-pinggaizi** [NNDam/adaface-partialfc#3]
![image](https://user-images.githubusercontent.com/52409244/206990118-1417164b-d3a7-4e9b-9f61-5d50386eacb5.png)
你好，patical_fc.py中为什么进行reduce_scatter操作呢，对训练会有影响吗

**Comment by qiu-pinggaizi** [comment]
@NNDam

**Comment by NNDam** [comment]
I just keep it from previous original insightface source code

**Comment by twmht** [comment]
@NNDam 

Why not using PartialFCV2(https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/partial_fc_v2.py)?

**Comment by NNDam** [comment]
> @NNDam
> 
> Why not using PartialFCV2(https://github.com/deepinsight/insightface/blob/master/recognition/arcface_torch/partial_fc_v2.py)?

I got some performance issues with partial_fc_v2 so I decided to use old version. And also have similar convergence problem :) (loss stuck at ~22 with config 5M ids 100M images cosface-R160-pfc0.1)

**Comment by twmht** [comment]
@NNDam 
I think there is a problem on your code (https://github.com/NNDam/adaface-partialfc/blob/master/losses.py#L75 and https://github.com/NNDam/adaface-partialfc/blob/master/losses.py#L77), those are not in-place operations.

**Comment by NNDam** [comment]
Fixed, thanks
